### ISSUE TITLE
Exception trying to parse an .ini file without sections

### ISSUE THREAD

**Issue by ddnomad** [danielquinn/python-php#1]
According to [Wikipedia article](https://en.wikipedia.org/wiki/INI_file) about INI configuration files it's possible for them to have no sections at all. PHP's INI parser supports such files. This lib is not which is sad. 

I assume this is a bug as it should work for any INI file. 

test INI that cannot be parsed:

> classname=ExampleTest

**Comment by danielquinn** [comment]
Wow, someone's actually using this?  I wrote it **years** ago and haven't looked at it since.  You're right though, this is definitely a bug.  I'll tag it as such and get to it when I can, but if you'd like to submit a PR, I'll update the package on PyPi with your fix.

**Comment by ddnomad** [comment]
Huh, yes. I'm porting a thing from PHP to Python and this package is
definitely what I need.

I'll try to look into it if I would meet my project deadlines. And if so
I'll submit a PR.

**Comment by danielquinn** [comment]
All fixed!  You can do a `pip install --upgrade php` or `git pull` from the master on this repo -- whichever you like, the fix should be there for you.

Important note: the documentation was out of sync with the code on the `strip_quotes=` feature.  I've made it so that it now defaults to `True`, so if that's not what you want, make sure you call it with `=False` for your own stuff.

If it's still broken for you, just reopen this ticket and I'll have another look.

Thanks for giving me an opportunity to take another look at this package :-)

**Comment by ddnomad** [comment]
Thank you a lot! I'll test it ASAP.
